/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package adivinhacao.gui;

/**
 *
 * @author migue
 */
public class JogoMult extends javax.swing.JPanel {

    /**
     * Creates new form JogoMult
     */
    public JogoMult() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_qntVidas = new javax.swing.JLabel();
        lbl_qntPontos = new javax.swing.JLabel();
        lbl_txtPontos = new javax.swing.JLabel();
        lbl_qntPulos = new javax.swing.JLabel();
        lbl_txtPulos = new javax.swing.JLabel();
        lbl_txtVidas = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txa_perg = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(51, 0, 0));
        setForeground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(800, 600));

        jPanel1.setBackground(new java.awt.Color(51, 0, 0));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        lbl_qntVidas.setBackground(new java.awt.Color(0, 0, 0));
        lbl_qntVidas.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        lbl_qntVidas.setForeground(new java.awt.Color(255, 153, 153));
        lbl_qntVidas.setText("5");

        lbl_qntPontos.setBackground(new java.awt.Color(0, 0, 0));
        lbl_qntPontos.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        lbl_qntPontos.setForeground(new java.awt.Color(153, 255, 153));
        lbl_qntPontos.setText("0");

        lbl_txtPontos.setBackground(new java.awt.Color(0, 0, 0));
        lbl_txtPontos.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        lbl_txtPontos.setForeground(new java.awt.Color(255, 255, 255));
        lbl_txtPontos.setText("Pontos:");

        lbl_qntPulos.setBackground(new java.awt.Color(0, 0, 0));
        lbl_qntPulos.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        lbl_qntPulos.setForeground(new java.awt.Color(255, 255, 153));
        lbl_qntPulos.setText("3");

        lbl_txtPulos.setBackground(new java.awt.Color(0, 0, 0));
        lbl_txtPulos.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        lbl_txtPulos.setForeground(new java.awt.Color(255, 255, 255));
        lbl_txtPulos.setText("Pulos:");

        lbl_txtVidas.setBackground(new java.awt.Color(0, 0, 0));
        lbl_txtVidas.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        lbl_txtVidas.setForeground(new java.awt.Color(255, 255, 255));
        lbl_txtVidas.setText("Vidas:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_txtPontos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_qntPontos))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_txtVidas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_qntVidas))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_txtPulos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_qntPulos)))
                        .addGap(8, 8, 8)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_txtPontos)
                    .addComponent(lbl_qntPontos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_qntVidas)
                    .addComponent(lbl_txtVidas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_txtPulos)
                    .addComponent(lbl_qntPulos))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel2.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 759, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 322, Short.MAX_VALUE)
        );

        jScrollPane2.setBackground(new java.awt.Color(51, 0, 51));
        jScrollPane2.setBorder(null);
        jScrollPane2.setForeground(new java.awt.Color(255, 51, 51));
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txa_perg.setEditable(false);
        txa_perg.setBackground(new java.awt.Color(51, 0, 51));
        txa_perg.setColumns(20);
        txa_perg.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        txa_perg.setForeground(new java.awt.Color(204, 204, 204));
        txa_perg.setLineWrap(true);
        txa_perg.setRows(12);
        txa_perg.setTabSize(2);
        txa_perg.setText("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa");
        txa_perg.setAutoscrolls(false);
        txa_perg.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(txa_perg);
        txa_perg.getAccessibleContext().setAccessibleParent(this);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(135, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JLabel lbl_qntPontos;
    public javax.swing.JLabel lbl_qntPulos;
    public javax.swing.JLabel lbl_qntVidas;
    private javax.swing.JLabel lbl_txtPontos;
    private javax.swing.JLabel lbl_txtPulos;
    private javax.swing.JLabel lbl_txtVidas;
    private javax.swing.JTextArea txa_perg;
    // End of variables declaration//GEN-END:variables
}
